#!/usr/bin/env bash
# Software Development Kit

readonly CXE_NAME="${CXE_NAME:-cxe}"
readonly CXE_ABBR="$(echo "$CXE_NAME" | tr [:lower:] [:upper:])"
readonly CXE_VERSION="0.2.0"
readonly CXE_COMMAND="/usr/local/bin/${CXE_NAME}"
readonly CXE_PROFILE="${HOME:-~}/.${CXE_NAME}/profile"

# return the current branch name
function _gitBranch() {
    git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

# convert string to lowercase
function _lowercase() {
    echo "$*" | tr '[:upper:]' '[:lower:]'
}

# convert string to uppercase
function _uppercase() {
    echo "$*" | tr '[:lower:]' '[:upper:]'
}

function _exit() {
    echo "$CXE_ABBR Error ($1): ${@:2}"
    exit $1
}

if [[ "$CXE_IMAGE" ]]; then
    PS1="\e[0;34m$CXE_IMAGE \w> \e[m"

else

    function --version() {
        echo "$CXE_VERSION"
    }

    function --help() {
        local functionNames="$(declare -F)"
        IFS=$'\n' read -rd '' -a functionNames <<<"${functionNames//declare -f /}"

        text=(
            "$(echo -e "\033[34;1m")"
            "${CXE_ABBR} Software Development Kit v${CXE_VERSION}"
            "$(echo -e "\033[0;34m")"
            "Usage: $(echo -e "\033[36m" "$CXE_NAME <COMMAND|DOCKER_IMAGE> <ARGS>" "\033[34m")"
            ''
            'COMMAND: any of'
        )
        for functionName in ${functionNames[@]}; do
            [[ "${functionName:0:1}" != "_" ]] && text+=("• $functionName")
        done

        text+=("$(echo -e "\033[0m")")
        local IFS=$'\n'
        echo "${text[*]}"
    }

    # install the command
    function --install() {
        if [[ -d "$CXE_DIR" ]] && [[ -f "$CXE_DIR/cli" ]] && [[ -L "$CXE_COMMAND" ]]; then
            echo -n "already "
        else
            mkdir -p ~/.cxe

            # reuse existing profile for some settings
            if [[ -f "$CXE_PROFILE" ]]; then
                source "$CXE_PROFILE"
            fi

            # regenerate and save profile
            data=(
                "export CXE_DIR='$PWD'"
                "export CXE_DEFAULT_AUTHOR='${CXE_DEFAULT_AUTHOR:-USER}'"
                'export PATH="$CXE_DIR:$PATH"'
            )
            local IFS=$'\n'
            echo "${data[*]}" >$CXE_PROFILE

            # add to bash-profile if not already there
            if ! grep -q "cxe/profile" ~/.bash_profile; then
                echo "source '$CXE_PROFILE'" >>~/.bash_profile
            fi

            # load the newly generated profile (also modifies PATH)
            source $CXE_PROFILE

            # expose command
            if [[ ! -f "$CXE_COMMAND" ]] && [[ ! -L "$CXE_COMMAND" ]]; then
                ln -s "$CXE_DIR/cli" "$CXE_COMMAND"
            else
                _exit 1 "'$CXE_COMMAND' already exits. Aborting."
            fi
        fi
        echo "installed $CXE_ABBR $CXE_VERSION: $CXE_COMMAND"
    }

    # uninstall the command
    function --uninstall() {
        [[ -L "$CXE_COMMAND" ]] && unlink "$CXE_COMMAND"
        [[ -f "$CXE_PROFILE" ]] && unlink "$CXE_PROFILE"
        export PATH="$(echo "${PATH//$CXE_DIR:/}")"
        export CXE_DIR=
        hash -r
        echo "uninstalled $CXE_ABBR"
    }

    if [ "$1" ]; then
        if [[ "$(type -t -- "$1")" ]]; then
            [[ "${1:0:1}" == "_" ]] && _exit 2 "restricted command '$1'"
            "$1" "${@:2}"
        else
            docker run --rm -it \
                -e "CXE_IMAGE=$1" \
                -w /app \
                -v $PWD:/app \
                -v $CXE_DIR:/cxe \
                "$1" bash --init-file /cxe/cli
        fi
    else
        --help
    fi
fi
